security:
    providers:
        users_db:
            entity: { class: 'AppBundle\Entity\User' }

    encoders:
        AppBundle\Entity\User: bcrypt

    access_decision_manager:
        strategy: unanimous

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            context: main_context
            provider: users_db
            switch_user:
                provider: users_db
            anonymous: true

            form_login:
                login_path: security_login
                check_path: security_login_check
                default_target_path: user_home
                username_parameter: _email
                password_parameter: _password
                remember_me: true
                csrf_token_generator: security.csrf.token_manager

            logout:
                path: security_logout
                target: home

            remember_me:
                secret: '%secret%'

    access_control:
        - { path: '^/profile', roles: ROLE_USER }
        - { path: '^/admin', roles: ROLE_ADMIN }
#        - { path: '^/admin/login', roles: [IS_AUTHENTICATED_ANONYMOUSLY] }
#        - { path: '^/admin/impersonation/exit', roles: [ROLE_PREVIOUS_ADMIN] }
#        - { path: '^/membre/.*', roles: IS_AUTHENTICATED_FULLY }
